# This is a basic workflow to help you get started with Actions

name: Short-Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the mydev branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-TITANV:
    runs-on: ubuntu-latest
    container:
      image: tgrogers/accel-sim_regress:Ubuntu-22.04-cuda-11.7
      env:
        CONFIG: TITANV
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run Simulation
        run: /bin/bash $GITHUB_WORKSPACE/short-tests.sh

  build-TITANV-LOCALXBAR:
    runs-on: ubuntu-latest
    container:
      image: tgrogers/accel-sim_regress:Ubuntu-22.04-cuda-11.7
      env:
        CONFIG: TITANV-LOCALXBAR
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run Simulation
        run: /bin/bash $GITHUB_WORKSPACE/short-tests.sh

  build-QV100:
    runs-on: ubuntu-latest
    container:
      image: tgrogers/accel-sim_regress:Ubuntu-22.04-cuda-11.7
      env:
        CONFIG: QV100
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run Simulation
        run: /bin/bash $GITHUB_WORKSPACE/short-tests.sh

  build-2060:
    runs-on: ubuntu-latest
    container:
      image: tgrogers/accel-sim_regress:Ubuntu-22.04-cuda-11.7
      env:
        CONFIG: RTX2060
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run Simulation
        run: /bin/bash $GITHUB_WORKSPACE/short-tests.sh

  build-3070:
    runs-on: ubuntu-latest
    container:
      image: tgrogers/accel-sim_regress:Ubuntu-22.04-cuda-11.7
      env:
        CONFIG: RTX3070
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run Simulation
        run: /bin/bash $GITHUB_WORKSPACE/short-tests.sh
